version: '3.9'

services:
  #service 1 : mysql
  db:
    image: mysql:latest
    container_name: mysql-db
    environment:
      - MYSQL_ROOT_PASSWORD=pass@word1
    ports:
      - "3307:3306"
    restart: always
   #service 2 : command Service
  commandService:
    image: command-service
    container_name: command-service-app
    build:
      context: .
      dockerfile: ./commandservice/Dockerfile
    ports:
      - "8082:8082"
    restart: always

    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/stock_market?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: pass@word1