version: '3'

services:
  #service 1 : mysql
  db:
    image: mysql:8.0.19
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: pass@word1
      MYSQL_DATABASE: stock_market
    ports:
      - "3307:3306"
    restart: always
    #service 2 : command Service
  commandService:
    image: command-service
    container_name: command-service-app
    build:
      context: .
      dockerfile: ./commandservice/Dockerfile
    ports:
      - "8082:8082"
    restart: always
    command: --spring.profiles.active=docker
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - db
      - kafka
      - apiGateway
    #service 3 : zookeeper
  zookeeper:
    image: wurstmeister/zookeeper:latest
    environment:
      ALLOW_ANONYMOUS_LOGIN: yes
    container_name: zookeeper
    restart: always
    ports:
      - "2181:2181"
    # service 4 : kafka
  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    hostname: kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "stock_market:1:1"
    #service 5 : queryservice
  queryService:
    image: query-service
    container_name: query-service-app
    build:
      context: .
      dockerfile: ./queryservice/Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - mongo_db
      - kafka
      - apiGateway
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    command: --spring.profiles.active=docker
    #service 6 : mongodb
  mongo_db:
    image: "mongo:4.4.3"
    restart: always
    ports:
      - 27018:27017
    #service 7 : OAuth Service
  authService:
    image: "auth-service"
    container_name: auth-service-app
    build:
      context: .
      dockerfile: ./authservice/Dockerfile
    ports:
      - "9191:9191"
    restart: always
    command: --spring.profiles.active=docker
    environment:
      SPRING_PROFILES_ACTIVE: docker
      MYSQL_ROOT_PASSWORD: pass@word1
      MYSQL_DATABASE: stock_market
    depends_on:
      - db
      - apiGateway
    #service 8: api-gateway
  apiGateway:
    image: "api-gateway"
    container_name: api-gateway-app
    build:
      context: .
      dockerfile: ./api-gateway/Dockerfile
    ports:
      - "8083:8083"
    restart: always
    command: --spring.profiles.active=docker
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - serviceRegistry
      #service 9: service-registry
  serviceRegistry:
    image:  "service-registry"
    container_name: service-registry-app
    build:
      context: .
      dockerfile: ./service-registry/Dockerfile
    ports:
      - "8761:8761"
    restart: always


