version: '3'

services:
  #service 1 : mysql
  db:
    image: mysql:8.0.19
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: pass@word1
      MYSQL_DATABASE: stock_market
    ports:
      - "3307:3306"
    restart: on-failure
   #service 2 : command Service
  commandService:
    image: command-service
    container_name: command-service-app
    build:
      context: .
      dockerfile: ./commandservice/Dockerfile
    ports:
      - "8082:8082"
    restart: on-failure
    depends_on:
      - db