spring:
  profiles: default
  application:
    name: api-gateway
server:
  port: 8083
zuul:
  routes:
    commandservice:
      path: /command/**
      serviceeId: COMMANDSERVICE
    queryservice:
      path: /query/**
      serviceId: QUERYSERVICE
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
  lease-renewal-interval-in-seconds: 30