spring:
  application:
    name: queryservice
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

  datasource:
    url: jdbc:mysql://localhost:3306/stock_market
    username: root
    password: pass@word1
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port : 8081

