spring:
  application:
    name: queryservice
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect

  datasource:
    url: jdbc:mysql://localhost:3306/stock_market?createDatabaseIfNotExist=true
    username: stock
    password: stock123
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port : 8081

